import { ModelConfig } from "@/types/image-editor";

export const GENERATION_MODELS: ModelConfig[] = [
  {
    id: "black-forest-labs/flux-schnell",
    name: "Flux Schnell",
    type: "generation",
    parameters: [
      {
        name: "prompt",
        type: "text",
        label: "Prompt",
      },
      {
        name: "aspect_ratio",
        type: "select",
        label: "Aspect Ratio",
        default: "1:1",
        options: [
          "1:1",
          "16:9",
          "21:9",
          "3:2",
          "2:3",
          "4:5",
          "5:4",
          "3:4",
          "4:3",
          "9:16",
          "9:21",
        ],
      },
      {
        name: "num_outputs",
        type: "range",
        label: "Number of Images",
        min: 1,
        max: 4,
        default: 1,
      },
      {
        name: "num_inference_steps",
        type: "range",
        label: "Inference Steps",
        min: 1,
        max: 4,
        default: 4,
      },
      {
        name: "seed",
        type: "number",
        label: "Seed",
      },
      {
        name: "output_format",
        type: "select",
        label: "Output Format",
        default: "webp",
        options: ["webp", "jpg", "png"],
      },
      {
        name: "output_quality",
        type: "range",
        label: "Output Quality",
        min: 0,
        max: 100,
        default: 80,
      },
      {
        name: "megapixels",
        type: "select",
        label: "Resolution",
        default: "1",
        options: ["1", "0.25"],
      },
    ],
  },
  {
    id: "black-forest-labs/flux-dev",
    name: "Flux Dev",
    type: "generation",
    parameters: [
      {
        name: "prompt",
        type: "text",
        label: "Prompt",
      },
      {
        name: "aspect_ratio",
        type: "select",
        label: "Aspect Ratio",
        default: "1:1",
        options: [
          "1:1",
          "16:9",
          "21:9",
          "3:2",
          "2:3",
          "4:5",
          "5:4",
          "3:4",
          "4:3",
          "9:16",
          "9:21",
        ],
      },
      {
        name: "num_outputs",
        type: "range",
        label: "Number of Images",
        min: 1,
        max: 4,
        default: 1,
      },
      {
        name: "guidance",
        type: "range",
        label: "Guidance Scale",
        min: 0,
        max: 10,
        step: 0.1,
        default: 3,
      },
      {
        name: "num_inference_steps",
        type: "range",
        label: "Inference Steps",
        min: 1,
        max: 50,
        default: 28,
      },
      {
        name: "seed",
        type: "number",
        label: "Seed",
      },
      {
        name: "output_format",
        type: "select",
        label: "Output Format",
        default: "webp",
        options: ["webp", "jpg", "png"],
      },
      {
        name: "output_quality",
        type: "range",
        label: "Output Quality",
        min: 0,
        max: 100,
        default: 80,
      },
      {
        name: "megapixels",
        type: "select",
        label: "Resolution",
        default: "1",
        options: ["1", "0.25"],
      },
    ],
  },
];

export const EDITING_MODELS: ModelConfig[] = [
  {
    id: "black-forest-labs/flux-fill-pro",
    name: "Flux Fill Pro",
    type: "editing",
    parameters: [
      {
        name: "prompt",
        type: "text",
        label: "Prompt",
      },
      {
        name: "steps",
        type: "range",
        label: "Steps",
        min: 1,
        max: 50,
        default: 50,
      },
      {
        name: "guidance",
        type: "range",
        label: "Guidance Scale",
        min: 2,
        max: 5,
        step: 0.1,
        default: 3,
      },
      {
        name: "seed",
        type: "number",
        label: "Seed",
      },
      {
        name: "output_format",
        type: "select",
        label: "Output Format",
        default: "jpg",
        options: ["jpg", "png"],
      },
      {
        name: "safety_tolerance",
        type: "range",
        label: "Safety Tolerance",
        min: 1,
        max: 6,
        default: 2,
      },
      {
        name: "prompt_upsampling",
        type: "select",
        label: "Prompt Upsampling",
        default: "false",
        options: ["true", "false"],
      },
    ],
  },
];
